version: "3.8"

# this is a YAML anchor to avoid repetition
x-logging: &logging
  logging:
    driver: loki 
    options: # note: the ip is the ip we will assign later to loki in this file
      loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
      loki-retries: "5"

services:
  # gitea is a demo service from which we want to extract logs
  gitea:
    logging:
      driver: loki 
      options: # note: the ip is the ip we will assign later to loki in this file
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
        loki-retries: "5"
    image: gitea/gitea:1.13.0
    container_name: gitea
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    entrypoint: ping host.docker.internal:3100
    # here I removed informations irrelevant to the issue
  
  # the loki instance
  loki:
    container_name: loki
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
