{
 "title": "Logs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{container_name=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Prometheus Log Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"prometheus\"}[1m]))"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Grafana Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{container_name=\"grafana\"}"
      }
     ]
    },
    {
     "title": "Grafana Log Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(count_over_time({container_name=\"grafana\"}[1m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "GetMetrics systemd Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "GetMetrics systemd Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "{filename= \"/var/log/syslog\",job=\"varlogs\"} |= \"get_system_metrics.sh\"",
       "legendFormat": "get_metrics.sh"
      }
     ]
    },
    {
     "title": "GetMetrics systemd Log Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(count_over_time({filename=\"/var/log/syslog\"} |= \"get_system_metrics.sh\" [1m]) )"
      }
     ]
    }
   ]
  },
  {
   "title": "Pushgateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pushgateway Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "{container_name=\"pushgateway\"}"
      }
     ]
    },
    {
     "title": "Pushgateway Log Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(count_over_time({container_name=\"pushgateway\"}[1m]))"
      }
     ]
    }
   ]
  }
 ]
}