{
 "title": "Top Processes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "AdhocFIlters", "label": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Top 3 CPU Processes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(3,cpu_usage)", "legendFormat": "{{process}} {{pid}}" }
   ]
  },
  {
   "title": "Top 3 MEM Processes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(3,mem_usage)", "legendFormat": "{{process}} {{pid}}" }
   ]
  },
  {
   "title": "Top CPU Processes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "topk(10,cpu_usage)", "legendFormat": "{{process}} {{pid}}" }
   ]
  },
  {
   "title": "Top Mem Processes",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "topk(10,mem_usage)", "legendFormat": "{{process}} {{pid}}" }
   ]
  },
  {
   "title": "HIstorical CPU Graph",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "topk(25,cpu_usage)" }
   ]
  },
  {
   "title": "HIstorical MEM Graph",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "topk(10,mem_usage)" }
   ]
  }
 ]
}